# Generated by Django 4.2.10 on 2024-03-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_moves', models.IntegerField()),
                ('board', models.TextField()),
                ('turn', models.CharField(max_length=1)),
                ('castling', models.CharField(max_length=4)),
                ('soft_moves', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.game')),
            ],
        ),
    ]
