# Generated by Django 4.2.10 on 2024-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enpassant',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
