# Generated by Django 4.2.10 on 2024-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_game_black_game_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[(None, 'None'), ('w', 'white'), ('b', 'black'), ('d', 'draw')], default=None, max_length=1, null=True),
        ),
    ]
