# Generated by Django 4.2.10 on 2024-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_game_started_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='white_ready',
            field=models.BooleanField(default=False),
        ),
    ]
