# Generated by Django 4.2.10 on 2024-06-18 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_board_black_time_left_board_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='black_time_left',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
        migrations.AlterField(
            model_name='board',
            name='white_time_left',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
