# Generated by Django 4.2.10 on 2024-08-07 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0008_alter_board_black_time_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWithAi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[(None, 'None'), ('w', 'white'), ('b', 'black'), ('d', 'draw')], default=None, max_length=1, null=True)),
                ('started', models.BooleanField(default=False)),
                ('white_ready', models.BooleanField(default=False)),
                ('white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_ai_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
