# Generated by Django 4.2.10 on 2024-08-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_board_game_with_ai_alter_board_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='game_with_ai',
        ),
        migrations.AlterField(
            model_name='board',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table.game'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameWithAi',
        ),
    ]
