# Generated by Django 4.2.10 on 2024-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_remove_board_game_with_ai_alter_board_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='with_ai',
            field=models.BooleanField(default=False),
        ),
    ]
