# Generated by Django 5.0.2 on 2024-09-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_game_with_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_move',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='boards',
            field=models.JSONField(default=list),
        ),
    ]
