# Generated by Django 5.0.2 on 2024-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0014_board_last_move_game_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='checking',
            field=models.JSONField(default=list),
        ),
    ]
