# Generated by Django 5.0.2 on 2024-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0015_board_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='white_draw',
            field=models.BooleanField(default=False),
        ),
    ]
