# Generated by Django 5.0.2 on 2024-10-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('table', '0016_game_black_draw_game_white_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.game'),
        ),
    ]
