# Generated by Django 5.0.2 on 2025-02-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_user_created_at_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
