# Generated by Django 5.0.2 on 2025-03-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_user_avatar'),
        ('table', '0017_game_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.game'),
        ),
    ]
